### ISSUE TITLE
Swagger 1 no longer works

### ISSUE THREAD

**Issue by ebaxt** [ardoq/ardoq-swagger-addon#12]
Tested with https://connect.gettyimages.com/swagger/api-docs

```
Channel closed
clojure.lang.ExceptionInfo: InvalidSwagger {:causes "[ {\n  \"level\" : \"error\",\n  \"schema\" : {\n    \"loadingURI\" : \"#\",\n    \"pointer\" : \"\"\n  },\n  \"instance\" : {\n    \"pointer\" : \"\"\n  },\n  \"domain\" : \"validation\",\n  \"keyword\" : \"required\",\n  \"message\" : \"object has missing required properties ([\\\"basePath\\\"])\",\n  \"required\" : [ \"apis\", \"basePath\", \"swaggerVersion\" ],\n  \"missing\" : [ \"basePath\" ]\n} ]"}
	at clojure.core$ex_info.invoke(core.clj:4403)
	at ardoq.swagger.api$version1.invoke(api.clj:50)
	at ardoq.swagger.api$get_spec.invoke(api.clj:73)
	at ardoq.swagger.api$swagger_api$fn__6358.invoke(api.clj:114)
	at compojure.core$make_route$fn__5913.invoke(core.clj:104)
	at compojure.core$wrap_route_middleware$fn__5909.invoke(core.clj:94)
	at compojure.core$if_route$fn__5895.invoke(core.clj:41)
	at compojure.core$if_method$fn__5887.invoke(core.clj:27)
	at compojure.core$routing$fn__5919.invoke(core.clj:118)
	at clojure.core$some.invoke(core.clj:2515)
	at compojure.core$routing.doInvoke(core.clj:118)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:626)
	at compojure.core$routes$fn__5923.invoke(core.clj:123)
	at ring.middleware.session$wrap_session$fn__7074.invoke(session.clj:98)
	at ring.middleware.params$wrap_params$fn__6413.invoke(params.clj:64)
	at org.httpkit.server.HttpHandler.run(RingHandler.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Importing swagger doc from  https://connect.gettyimages.com/swagger/api-docs . Custom headers nil
WebSocket channel

Response from  https://connect.gettyimages.com/swagger/api-docs

clojure.lang.ArityException: Wrong number of args (2) passed to: socket/socket-send
	at clojure.lang.AFn.throwArity(AFn.java:429)
	at clojure.lang.AFn.invoke(AFn.java:36)
	at ardoq.swagger.api$version1.invoke(api.clj:43)
	at ardoq.swagger.api$get_spec.invoke(api.clj:73)
	at ardoq.swagger.api$swagger_api$fn__6358.invoke(api.clj:114)
	at compojure.core$make_route$fn__5913.invoke(core.clj:104)
	at compojure.core$wrap_route_middleware$fn__5909.invoke(core.clj:94)
	at compojure.core$if_route$fn__5895.invoke(core.clj:41)
	at compojure.core$if_method$fn__5887.invoke(core.clj:27)
	at compojure.core$routing$fn__5919.invoke(core.clj:118)
	at clojure.core$some.invoke(core.clj:2515)
	at compojure.core$routing.doInvoke(core.clj:118)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:626)
	at compojure.core$routes$fn__5923.invoke(core.clj:123)
	at ring.middleware.session$wrap_session$fn__7074.invoke(session.clj:98)
	at ring.middleware.params$wrap_params$fn__6413.invoke(params.clj:64)
	at org.httpkit.server.HttpHandler.run(RingHandler.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

@Molyna Could you have a look?

**Comment by Molyna** [comment]
There was a  wrong setup with socket in regards to validation for swagger 1. This is fixed with 5cfe06083b5e43125ffb60e5665c951fe5c2394a

The swagger at the url in the error message doesn't pass validation and therefore will throw an exception unless the validation is ignored.

**Comment by ebaxt** [comment]
@Molyna But don't you think we should send the validation error to the user over the web socket? Instead of a 500 error?

**Comment by Molyna** [comment]
The application is meant to print in the error message on screen while using the addon however. Fixing that right now as something is missing.

We can move it to the socket but a bit of a bigger fix.

**Comment by ebaxt** [comment]
https://github.com/ardoq/ardoq-swagger-addon/issues/13
